# _config.yml
baseurl: "/ug-ml-notes" # <-- repo name
url: "https://utkarshgarg-ug.github.io"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
